# Generated by Django 6.0.6 on 2026-06-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('projects', '0004_alter_project_options_project_brochure_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('project', 'email'), name='unique_project_email'),
        ),
    ]
