# Generated by Django 6.0.6 on 2026-06-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_project_brochure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='brochure',
        ),
    ]
